.TH GNUPOD_OTGSYNC "23" "June 2005" "gnupod_otgsync.pl 0.98.1" "User Commands"
.SH NAME
gnupod_otgsync.pl \- manual page for gnupod_otgsync.pl 0.98.1
.SH SYNOPSIS
.B gnupod_otgsync.pl
[\fIOPTION\fR]...
.SH DESCRIPTION
Helper script for On-The-Go stuff. Not for humans, called by GNUpod.
.SH AUTHOR
Written by Adrian Ulrich
.SH "REPORTING BUGS"
Report bugs to <bug-gnupod@nongnu.org>
.SH COPYRIGHT
Copyright \(co Adrian Ulrich
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
The full documentation for
.B gnupod
is maintained as a Texinfo manual.  If the
.B info program
and
.B GNUpod
are properly installed at your site, the command
.IP
.B info gnupod
.PP
should give you access to the complete manual.
