.TH GNUPOD_CHECK "1" "June 2004" "gnupod_check.pl 0.95" "User Commands"
.SH NAME
gnupod_check.pl \- manual page for gnupod_check.pl 0.95
.SH SYNOPSIS
.B gnupod_check.pl
[\fIOPTION\fR]...
.SH DESCRIPTION
Check for lost/zombie files on the iPod.
Use this tool if your OS crashed while uploading songs to the iPod or if you have too much time ;)
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.TP
\fB\-m\fR, \fB\-\-mount=DIRECTORY\fR
iPod mountpoint. Default is $IPOD_MOUNTPOINT
.SH AUTHOR
Written by Adrian Ulrich
.SH "REPORTING BUGS"
Report bugs to <bug-gnupod@nongnu.org>
.SH COPYRIGHT
Copyright \(co Adrian Ulrich
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
The full documentation for
.B gnupod
is maintained as a Texinfo manual.  If the
.B info program
and
.B GNUpod
are properly installed at your site, the command
.IP
.B info gnupod
.PP
should give you access to the complete manual.
