.TH GNUPOD_SEARCH "1" "February 2005" "gnupod_search.pl 0.98" "User Commands"
.SH NAME
gnupod_search.pl \- manual page for gnupod_search.pl 0.98
.SH SYNOPSIS
.B gnupod_search.pl
[\fIOPTION\fR]...
.SH DESCRIPTION
Search and Remove files
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.TP
\fB\-m\fR, \fB\-\-mount=DIRECTORY\fR
iPod mountpoint. Default is $IPOD_MOUNTPOINT
.TP
\fB\-t\fR, \fB\-\-title=STRING\fR
search songs by Title
.TP
\fB\-a\fR, \fB\-\-artist=STRING\fR
search songs by Artist
.TP
\fB\-l\fR, \fB\-\-album=STRING\fR
search songs by Album
.TP
\fB\-i\fR, \fB\-\-id=INT\fR
search songs by ID
.TP
\fB\-g\fR, \fB\-\-genre=STRING\fR
search songs by Genre
.TP
\fB\-o\fR, \fB\-\-match\-once\fR
Search does not need to match multiple times (like ($a || $b || $c))
.TP
\fB\-\-delete\fR
Remove (!) matched songs from the iPod
.TP
\fB\-\-view=ialt\fR
Modify output, default is 'ialt'

t = title    a = artist   r = rating      p = path

l = album    g = genre    c = playcount   i = id
.TP
\fB\-\-rename="KEY=VALUE"\fR
Rename KEY into VALUE for matched songs.

Example: Rename the Artist 'Jon Doe' into 'Jo\fBh\fRn Doe'

gnupod_search.pl --artist="Jon Doe" --rename="artist=John Doe"

.SH AUTHOR
Written by Adrian Ulrich
.SH "REPORTING BUGS"
Report bugs to <bug-gnupod@nongnu.org>
.SH COPYRIGHT
Copyright \(co Adrian Ulrich
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
The full documentation for
.B gnupod
is maintained as a Texinfo manual.  If the
.B info program
and
.B GNUpod
are properly installed at your site, the command
.IP
.B info gnupod
.PP
should give you access to the complete manual.
