.TH GNUPOD_INIT "1" "July 2004" "gnupod_INIT.pl 0.97" "User Commands"
.SH NAME
gnupod_INIT.pl \- manual page for gnupod_INIT.pl 0.97
.SH SYNOPSIS
.B gnupod_INIT.pl
[\fIOPTION\fR]...
.SH DESCRIPTION
Prepares a 'virgin' iPod for GNUpod
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.TP
\fB\-m\fR, \fB\-\-mount=DIRECTORY\fR
iPod mountpoint. Note, gnupod_INIT.pl ignores $IPOD_MOUNTPOINT
.TP
\fB\-d\fR, \fB\-\-disable\-convert\fR
Don't try to convert an existing iTunesDB (Only for experts)
.TP
\fB\-f\fR, \fB\-\-france\fR
Create IPOD_MOUNTPOINT/iPod_Control/Device/Limit. This File tells iPods with Firmware 1.x to limit the
Volume to 100dB (EU/France law...). Firmware 2.x ignores this File. (But you can use the \-\-volume 
switch of mktunes.pl)
.SH AUTHOR
Written by Adrian Ulrich
.SH "REPORTING BUGS"
Report bugs to <bug-gnupod@nongnu.org>
.SH COPYRIGHT
Copyright \(co Adrian Ulrich
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
The full documentation for
.B gnupod
is maintained as a Texinfo manual.  If the
.B info program
and
.B GNUpod
are properly installed at your site, the command
.IP
.B info gnupod
.PP
should give you access to the complete manual.
