.TH MKTUNES "1" "July 2004" "mktunes.pl 0.97" "User Commands"
.SH NAME
mktunes.pl \- manual page for mktunes.pl 0.97
.SH SYNOPSIS
.B mktunes.pl
[\fIOPTION\fR]...
.SH DESCRIPTION
Convert GNUtunesDB.xml into iTunesDB format
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.TP
\fB\-m\fR, \fB\-\-mount=DIRECTORY\fR
iPod mountpoint. Default is $IPOD_MOUNTPOINT
.TP
\fB\-n\fR, \fB\-\-ipod\-name=NAME\fR
iPod Name (For unlabeled iPods). iTunes displays this name, not the label.
.TP
\fB\-v\fR, \fB\-\-volume=VALUE\fR
Adjust volume +\-VALUE% (example: \-\-volume +5)
.TP
\fB\-e\fR, \fB\-\-energy\fR
Save energy (= Disable scrolling title)
.SH AUTHOR
Written by Adrian Ulrich
.SH "REPORTING BUGS"
Report bugs to <bug-gnupod@nongnu.org>
.SH COPYRIGHT
Copyright \(co Adrian Ulrich
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
The full documentation for
.B gnupod
is maintained as a Texinfo manual.  If the
.B info program
and
.B GNUpod
are properly installed at your site, the command
.IP
.B info gnupod
.PP
should give you access to the complete manual.
