.TH TUNES2POD "1" "June 2005" "tunes2pod.pl 1.00" "User Commands"
.SH NAME
tunes2pod.pl \- manual page for tunes2pod.pl 1.00
.SH SYNOPSIS
.B tunes2pod.pl
[\fIOPTION\fR]...
.SH DESCRIPTION
Convert an iTunesDB into XML (aka GNUtunesDB.xml)
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.TP
\fB\-m\fR, \fB\-\-mount=DIRECTORY\fR
iPod mountpoint. Default is $IPOD_MOUNTPOINT
.TP
\fB\-\-force\fR
Disable 'sync' checking. tunes2pod.pl may do stupid things :)
.SH AUTHOR
Written by Adrian Ulrich
.SH "REPORTING BUGS"
Report bugs to <bug-gnupod@nongnu.org>
.SH COPYRIGHT
Copyright \(co Adrian Ulrich
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
The full documentation for
.B gnupod
is maintained as a Texinfo manual.  If the
.B info program
and
.B GNUpod
are properly installed at your site, the command
.IP
.B info gnupod
.PP
should give you access to the complete manual.
